name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Permet de lancer le build manuellement si besoin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      # On cible spécifiquement l'app Android pour éviter les erreurs iOS
      run: ./gradlew :androidApp:assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mon-application-android
        path: androidApp/build/outputs/apk/debug/androidApp-debug.apk
